---
version: '3'
services:
  db:
    image: mysql:5
    environment:
      MYSQL_DATABASE: database1
      MYSQL_USER: database1_user
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: rootP@ssw0rd
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', '$$MYSQL_USER', '-p', '$$MYSQL_ROOT_PASSWORD' ]
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/mysql
    networks:
      - net

  packaging:
    build:
      context: ./packaging
      dockerfile: Dockerfile
    volumes:
      - app:/home/git/App42PaaS-Java-MySQL-Sample/target/
      - webcontent:/home/git/App42PaaS-Java-MySQL-Sample/WebContent/

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - app:/usr/local/tomcat/webapps/
      - webcontent:/usr/local/tomcat/ROOT/
    networks:
      - net

volumes:
  db:
  app:
  webcontent:
networks:
  net:
---